### ISSUE TITLE
Issue installing with pip

### ISSUE THREAD

**Issue by Abdol** [John-P/wsic#151]
- wsic version: 0.9.0
- Python version: 3.9.18
- Operating System: Ubuntu 22.04.3 LTS

### Description

I have tried installing the package with pip, following the [docs](https://wsic.readthedocs.io/en/latest/installation.html). Despite the package being successfully installed according to pip, when I run wsic from the terminal I get a missing dependency error. This shouldn't normally happen because I expect dependency to be installed with the pip command unless otherwise mentioned in the docs.

#### Installing with pip:
```
$ pip install wsic
Collecting wsic
  Downloading wsic-0.9.0-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.8/118.8 kB 6.9 MB/s eta 0:00:00
Requirement already satisfied: zarr in ./miniconda3/lib/python3.9/site-packages (from wsic) (2.14.2)
Requirement already satisfied: numpy in ./miniconda3/lib/python3.9/site-packages (from wsic) (1.26.4)
Requirement already satisfied: asciitree in ./miniconda3/lib/python3.9/site-packages (from zarr->wsic) (0.3.3)
Requirement already satisfied: numcodecs>=0.10.0 in ./miniconda3/lib/python3.9/site-packages (from zarr->wsic) (0.12.1)
Requirement already satisfied: fasteners in ./miniconda3/lib/python3.9/site-packages (from zarr->wsic) (0.19)
Installing collected packages: wsic
Successfully installed wsic-0.9.0
```
#### Trying wsic
```
$ wsic
Traceback (most recent call last):
  File "/home/USER/miniconda3/bin/wsic", line 5, in <module>
    from wsic.cli import main
  File "/home/USER/miniconda3/lib/python3.9/site-packages/wsic/__init__.py", line 7, in <module>
    from . import codecs, magic, metadata, multiproc, readers, typedefs, writers
  File "/home/USER/miniconda3/lib/python3.9/site-packages/wsic/readers.py", line 9, in <module>
    import xarray as xr
ModuleNotFoundError: No module named 'xarray'
```
#### Update 1
When trying to manually install `xarray` after getting the above error message, I get a similar dependency error concerning `dask`:

```
$ wsic
Traceback (most recent call last):
  File "/home/u2271662/miniconda3/envs/wsic/bin/wsic", line 5, in <module>
    from wsic.cli import main
  File "/home/USER/miniconda3/envs/wsic/lib/python3.9/site-packages/wsic/__init__.py", line 7, in <module>
    from . import codecs, magic, metadata, multiproc, readers, typedefs, writers
  File "/home/USER/miniconda3/envs/wsic/lib/python3.9/site-packages/wsic/writers.py", line 34, in <module>
    from wsic.tile_iterators import DaskTileIterator
  File "/home/USER/miniconda3/envs/wsic/lib/python3.9/site-packages/wsic/tile_iterators.py", line 11, in <module>
    import dask.distributed as daskd
ModuleNotFoundError: No module named 'dask'
****
```

#### Update 2
Installing from source did not fix the problem, too.

**Comment by chetana348** [comment]
I had a similar issue and had to manually install those two packages. Dask distributed can be installed using conda install dask distributed. Additionally, I also had to upgrade the Numpy for wsic to work.
