### ISSUE TITLE
BUG: Queues Python library fails on MacOS

### ISSUE THREAD

**Issue by ghadjigeorghiou** [John-P/wsic#2]
* wsic version: 0.2.0 (installed from wheel)
* Python version: 3.9.11 (Conda Environment)
* Operating System: MacOS Monterey Version 12.1 

### Description

I was trying to convert a JP2 image (size: 71.3Mb) to tiff. The wsic library failed because the Queues library threw a NotImplementedError. The creators of the library are aware of this issue since the code that throws the error has this comment

```python
    def qsize(self):
        # Raises NotImplementedError on Mac OSX because of broken sem_getvalue()
        return self._maxsize - self._sem._semlock._get_value()
```

### What I Did
Command
```bash
wsic convert -i ./<input_path>.jp2 -o ./1.tiff -rt 4096 4096 -w 1 --overwrite --no-ome -to 600
```
Error
```python
Traceback (most recent call last):
  File "/opt/miniconda3/envs/wsic/bin/wsic", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/wsic/cli.py", line 139, in convert
    writer.copy_from_reader(
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/wsic/writers.py", line 527, in copy_from_reader
    tif.write(
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/tifffile/tifffile.py", line 2660, in write
    for tileindex, chunk in enumerate(
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/tifffile/tifffile.py", line 16817, in encode_tiles
    tile = next(tileiter)
  File "/opt/miniconda3/envs/wsic/lib/python3.9/site-packages/wsic/readers.py", line 281, in __next__
    print(f"Queue Size {self.queue.qsize()}")
  File "/opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

The code keeps running after this error is thrown. When I stop it with ctrl + c, it throws this error

```python
Traceback (most recent call last):
  File "/opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
Process Process-1:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/queues.py", line 201, in _finalize_join
    thread.join()
  File "/opt/miniconda3/envs/wsic/lib/python3.9/threading.py", line 1053, in join
    self._wait_for_tstate_lock()
  File "/opt/miniconda3/envs/wsic/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
(wsic) ghadjigeorgiou@192 jp2tiff % /opt/miniconda3/envs/wsic/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by ghadjigeorghiou** [comment]
[StackOverflow discussion](https://stackoverflow.com/questions/65609529/python-multiprocessing-queue-notimplementederror-macos)

[Example of custom implementation that solves this](https://github.com/vterron/lemon/blob/d60576bec2ad5d1d5043bcb3111dff1fcb58a8d6/methods.py#L536-L573)

**Comment by John-P** [comment]
Thanks for identifying this. I have a fix in mind, I can manually keep track of the queue size with a shared counter.

**Comment by John-P** [comment]
@ghadjigeorghiou This should be addressed in https://github.com/John-P/wsic/commit/704a157772822e87ded36700c7abf94874131554

**Comment by ghadjigeorghiou** [comment]
Thanks @John-P
